# Generated by Django 5.2.3 on 2025-06-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_address_building_name_remove_address_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_preference_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_status', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('expected_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_at_mama_mboga', models.CharField(max_length=50)),
                ('mama_mboga', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.mamamboga')),
            ],
        ),
    ]
