# Generated by Django 5.2.3 on 2025-06-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='pickup_address',
            new_name='customer_address',
        ),
    ]
