# Generated by Django 5.2.3 on 2025-06-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_address_building_name_remove_address_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password_hash',
            new_name='password',
        ),
    ]
