# Generated by Django 5.2.3 on 2025-06-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_password_hash_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mamamboga',
            old_name='password_hash',
            new_name='password',
        ),
    ]
