# Generated by Django 5.2.3 on 2025-07-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mamamboga',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
