# Generated by Django 5.2.3 on 2025-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietarypreference',
            name='dietary_type',
            field=models.CharField(choices=[('VEGAN', 'Vegan'), ('KETO', 'Keto'), ('PALEO', 'Paleo'), ('GLUTEN_FREE', 'Gluten-Free'), ('DAIRY_FREE', 'Dairy-Free'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dietarypreference',
            name='excluded_ingredients',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='dietarypreference',
            name='favorite_cuisines',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='dietarypreference',
            name='nutritional_goal',
            field=models.CharField(choices=[('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain'), ('MAINTENANCE', 'Maintenance'), ('HEALTHY_EATING', 'Healthy Eating')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dietarypreference',
            name='preferred_meal_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
