# Generated by Django 4.2.23 on 2025-07-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20250718_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietarypreference',
            name='dietary_type',
            field=models.CharField(choices=[('VEGAN', 'Vegan'), ('KETO', 'Keto'), ('PALEO', 'Paleo'), ('GLUTEN_FREE', 'Gluten-Free'), ('DAIRY_FREE', 'Dairy-Free'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
