# Generated by Django 5.2.3 on 2025-06-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payout_delete_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
