# Generated by Django 5.2.4 on 2025-07-24 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_preference_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_status', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('expected_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.customer')),
                ('customer_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.address')),
                ('mama_mboga', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.mamamboga')),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_at_mama_mboga', models.CharField(max_length=50)),
                ('mama_mboga', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.mamamboga')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
