# Generated by Django 5.2.4 on 2025-07-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='item_total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
