# Generated by Django 5.2.3 on 2025-07-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_unit', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KSH', max_length=3)),
                ('current_stock_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_stock_update', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('mama_mboga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mamamboga')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
