# Generated by Django 5.2.4 on 2025-07-24 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mama_mboga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.mamamboga'),
            preserve_default=False,
        ),
    ]
